### ISSUE TITLE
Single webpack alias

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#1009]
Currently we are using too many webpack aliases which results in complicated maintenance, various problems with tooling, etc.

Let's settle on a single alias for internal code paths (excluding @globalfishingwatch/* modules).

To be changed in: 
- jsconfig.json
- webpack config
  
Module branch should be merged first.

**Comment by j8seangel** [comment]
https://github.com/GlobalFishingWatch/map-client/pull/1024
