### ISSUE TITLE
When loading custom raster layer, the layer name the user entered is not preserved

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#1022]
1st got to the map
2nd add custom layers
3rd click raster
4th add this raster url: https://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default//GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpg 
5th add a layer name, for example `NASA Night Lights`
6th save
7th go to the layers tab, you will see that `NASTA NIght Lights` is not present, instead you see `Layers Name`

**Comment by nerik** [comment]
@enriquetuya Fixed on `develop`
