### ISSUE TITLE
Changes before merging devel(with map-as-module) to master

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#1030]
* [ ]  Update Changes.md file, it seems we haven't updated it in the latest PR merges. A couple I recall: 
  - implemented map as a module.
  - implemented the Canonical URLS
  - implemented the Tagmanager logic
  - Implememted bablic code
  - changes in the environment variable
* [ ] Make sure we have map-as-module repository tagged with the latest version. Where is the map-module repo? Or we haven't extracted it yet?

**Comment by j8seangel** [comment]
> * Update Changes.md file, it seems we haven't updated it in the latest PR merges. A couple I recall:

https://github.com/GlobalFishingWatch/map-client/pull/1031 updates the changelog and the package.json with the current version, should be ready to deploy once merged.

> [ ] Make sure we have map-as-module repository tagged with the latest version. Where is the map-module repo? Or we haven't extracted it yet?

The repo is here: https://github.com/GlobalFishingWatch/map-components it also includes other components reused in the gfw environment.
