### ISSUE TITLE
Search by geography

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#664]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/recEnzrSwvQnIhAbl

**Comment by nerik** [comment]
@enriquetuya This is not a trivial task. Let me know if this is is still something we want to do.

**Comment by enriquetuya** [comment]
@nerik closing this one for now. We will be keeping the high level tasks `wish-list` on airtable.
