### ISSUE TITLE
Show more information on layer pop-ups

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#682]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/rec1k57vJlVFUHktl

**Comment by tiagojsag** [comment]
- [ ] implement some sort of "layer info mode" that allows users to click on polygons of a specific layer
- [ ] show modal with info on that polygon

**Comment by nerik** [comment]
Reuse lat/lon format from https://github.com/vizzuality/globalfishingwatch/issues/713
