### ISSUE TITLE
Protected Planet MPA overlay

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#685]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/rec1US0sZSrlPphnb

**Comment by tiagojsag** [comment]
@nerik and @enriquetuya need to discuss this in more detail

**Comment by nerik** [comment]
BC issue / TMS conversation: https://basecamp.com/1756858/projects/12049853/todos/317909410
