### ISSUE TITLE
New UI for map zoom/share/map search

### ISSUE THREAD

**Issue by tiagojsag** [GlobalFishingWatch/map-client#713]
- [x] move zoom in /out and share buttons 
- [ ] add new "search" button
- [ ] implement the search mini-modal
- [ ] Show lat long and implement the copy-paste for them
- [ ] Implement the search input
- [ ] Link with search functionality from https://github.com/Vizzuality/GlobalFishingWatch/issues/714

**Comment by nerik** [comment]
For lat/lon formatting: https://www.npmjs.com/formatcoords
👍 👍 👍 👍 👍
