### ISSUE TITLE
"Focus on map" feature for pinned vessels

### ISSUE THREAD

**Issue by tiagojsag** [GlobalFishingWatch/map-client#727]

**Comment by enriquetuya** [comment]
Duplicates: https://github.com/Vizzuality/GlobalFishingWatch/issues/673

**Comment by nerik** [comment]
Related: https://github.com/GlobalFishingWatch/map-client/issues/930#issuecomment-407412291

**Comment by enriquetuya** [comment]
Done for the mapbox release.
