### ISSUE TITLE
On FF, search placehodler text has the wrong color

### ISSUE THREAD

**Issue by tiagojsag** [GlobalFishingWatch/map-client#788]
![image](https://user-images.githubusercontent.com/973964/31214229-955010ea-a9aa-11e7-8f1c-674169247567.png)

**Comment by Bluesmile82** [comment]
![image](https://user-images.githubusercontent.com/9701591/31215427-b2435a72-a9af-11e7-8b0e-9a8d62070942.png)
Ariadna told me to change this color to a brighter blue to make it more readable

**Comment by tiagojsag** [comment]
completely agree with the change, and I see it fine on chrome, just not on FF. please fix

**Comment by nerik** [comment]
Not fixed on master.
