### ISSUE TITLE
Argentina zoomed out filtering issue

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#795]
(reported by Jamie)

hey Erik I just tested the new filter field and thin i found a bug
argentina long line filter, looking at argentina at normal zoom i get this:

![screen shot 2017-10-12 at 08 04 10](https://user-images.githubusercontent.com/1583415/31484761-d8aaa530-af31-11e7-8df0-dfa072c3be89.png)

zoom in by one and i get this

![screen shot 2017-10-12 at 08 04 40](https://user-images.githubusercontent.com/1583415/31484773-e0ac9428-af31-11e7-9e04-2286fa4b309f.png)

Is filtering applied on heatmap lost at zoom?

**Comment by nerik** [comment]
I think this uncovers an issue with the tileset we are using, also in production.

We noticed some areas (coast of Argentina, around France) are empty of any vessel activity for the year 2016:
![screen shot 2017-10-16 at 16 12 04](https://user-images.githubusercontent.com/1583415/31616366-d3bba304-b28c-11e7-9ce6-16e1d7c20911.png)
![screen shot 2017-10-16 at 16 12 11](https://user-images.githubusercontent.com/1583415/31616367-d3da5a6a-b28c-11e7-8037-490901468e2c.png)

While very active looking at 2017 data:

![screen shot 2017-10-16 at 16 12 22](https://user-images.githubusercontent.com/1583415/31616389-e242cb5a-b28c-11e7-876f-3e7666e305d2.png)
![screen shot 2017-10-16 at 16 12 24](https://user-images.githubusercontent.com/1583415/31616390-e25d4f34-b28c-11e7-84b6-e81ae0d8a17a.png)

(with the same range displayed, one month)

In the case of Argentina, the raw tile (just after processed by the pelagos client code) contains 6000 points in total, but zero within that bounding box :

![screen shot 2017-10-16 at 16 14 35](https://user-images.githubusercontent.com/1583415/31616521-2ef9fbee-b28d-11e7-9ae3-ddbc07dd82ee.png)

While for 2017, we get about 8000 points total and 4000 points within the bbox.

I have checked the legacy map and it doesn't have that problem, but I wanted to check with you if the particular endpoint we are using could be the problem.

**Comment by enriquetuya** [comment]
@nerik In order to review this issue I will need more information:
1- A workspace showing the time extent you have selected, this will let me see exactly which tiles you are using.
2- The filters you are applying
3- Jaime mentions he has filter by long-line in argentina, but I don't recall sending you a full tileset with AIS filters on it.

**Comment by nerik** [comment]
Hi Enrique.

Of course:
1. http://globalfishingwatch.org/map/workspace/udw-v2-7544a144-96f9-44e2-9929-f44048beeb4e
You'll notice how the area mentioned stays empty from 01/01/2016 to 31/12/2016
2/3. I understand the confusion since the initial issue mentions filters, but this is not related, as the issue happens in production.

**Comment by enriquetuya** [comment]
Thanks for reporting the issue @nerik we will look into this.

**Comment by nerik** [comment]
@enriquetuya Just checked and this is still happening in production. Should I create a ticket in GFW-tasks? In any case this doesn't belong here, closing.
