### ISSUE TITLE
LImit the number of reportable regions that can be added

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#827]
Originally: https://basecamp.com/1756858/projects/12049853/todos/308309075

@enriquetuya  I'm not clear if it's an API limitation or an UI issue.

**Comment by enriquetuya** [comment]
@nerik actually is on both ends. WE can add the max on the API land but you will need to support that on the UI. The goal is to limit the number of polygons the number select, right now you can select as many as you want. I think with the current architecture the report will work, but it will do a very expensive query.

**Comment by nerik** [comment]
Ok then it's essentially a design issue as Tiago mentioned in the original ticket.
In parallel we should decide how to configure that, and it seems it's something that should be controlled by the API. Is that related to each individual heatmap layer? (in which case we'd use layer headers)
