### ISSUE TITLE
Need a way of user accessing layers info without having to trigger reports

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#829]
Enrique:
Tiago, Erik, right now the only way for a user to know details of the layer regions (mpa, eez, rfmo, etc) is clicking reports and then hovering. What can we do to make the user able of accessing the information easily?

Maybe clicking on the borders is an option to get started?

https://basecamp.com/1756858/projects/12049853/todos/309086699

**Comment by nerik** [comment]
@enriquetuya I believe this requires a bit more thought: I don't think having heatmap layers and regions clickable at the same time is a good option as it will lead to a lot of unwanted actions triggered. At the very least maybe, regions should only be clickable when all heatmap layers are toggled off.

**Comment by enriquetuya** [comment]
@nerik check that you have already proposed a solution to this which was accepted: https://projects.invisionapp.com/share/29D3LYPDQ#/screens/249298371

**Comment by nerik** [comment]
Yes you're right, my bad

**Comment by enriquetuya** [comment]
Will be fixed in the mapbox branch :)
