### ISSUE TITLE
KML layers not displaying

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#857]
The add KML layer functionality is not working. I've tried with several layers that used to work and they are not working anymore. 

Here is an example: 
https://www.dropbox.com/s/hnez3dohsj0rpoi/major_fao.kml?dl=1

**Comment by nerik** [comment]
I had a quick look and at a first glance there's nothing wrong on the client side, nor in the API service. The functionality works as intended when using the example KML file provided in the Google Maps docs (https://developers.google.com/maps/documentation/javascript/examples/layer-kml)

Could it be related to #843 ? (KML style attributes issue)

@enriquetuya when you say 'used to work', do you recall more or less when?

**Comment by enriquetuya** [comment]
@nerik I found a layer that a user asked me for help back in October 2017 and it still works: 
`https://www.dropbox.com/s/adbs9f5ucxq77or/test_klm-3-.kml?dl=1`

So it seems that in some cases this still work?

**Comment by nerik** [comment]
@enriquetuya I think we can close this one as the feature has been abandoned anyways

**Comment by enriquetuya** [comment]
@nerik yes, I agree. Closing this ticket since we are deprecating the KML functionality torwards the GEOJSON one: https://github.com/GlobalFishingWatch/GFW-Tasks/issues/703
