### ISSUE TITLE
Renderer is displaying tiles from lower zoom level

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#887]
Grid patterns are being displayed on the map. Are we using different tiles from the ones used on the current map? 

![screenshot 2018-05-09 12 58 57](https://user-images.githubusercontent.com/355597/39825670-c5bba6a8-5388-11e8-9702-c2c86524eb20.png)

**Comment by nerik** [comment]
Fixed by loading tiles at `z + 0.5` zoom level.
This can easily be fine-tuned to manage level of detail / bandwidth.

**Comment by enriquetuya** [comment]
Tried it out. Looks much better. 
I like the idea to check the bandwidth.
