### ISSUE TITLE
Continuous zoom vs discrete rendering of tiles issue

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#889]
The continuous zoom level and the discrete rendering of the fishing effort feels weird. The current version works like this:
	- you zoom, the zoom starts and then stops.
	- you see the old zoom level fishing heatmap
	- the old zoom fishing heatmap disappears
	- the new zoom fishing heatmap appears
I think if we hide the fishing effort when the user does the zoom and then when the zooms finishes we render the new level heatmap it will look better. The awesome solution would be like a continuous transition of the heatmap also, but that may not be doable since you need to query the new level zoom in advance, but may work when the results are cached. 

Proposed by @nerik :
>I agree, the problem being loss of context. A simple first fix: remove the step "the old zoom fishing heatmap disappears". ie the fishing heatmap from the previous zoom level stays on screen until new zoom level gets loaded.

**Comment by nerik** [comment]
Fixed on the mapbox branch, by waiting for all tiles to be loaded to dispose tiles that don't belong to the current zoom level.

While still noticeable this creates a much smoother visual transition.

**Comment by enriquetuya** [comment]
Tried it out. Looks much better.
