### ISSUE TITLE
Static Layer icon alignment issue

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#890]
Info and Color icons does not align to the layer name. Check MPA - no take. I think it has to do with the `protected planet WDPA…` being so long .

![screenshot 2018-05-09 13 07 27](https://user-images.githubusercontent.com/355597/39826079-f158ea7c-5389-11e8-82a0-5b4eae264ec0.png)

**Comment by nerik** [comment]
@enriquetuya I was not able to reproduce this one. Tested configurations:
- OSX Chrome, FF, Safari
- Win10 Edge, Chrome
- Ubuntu Chromium

**Comment by enriquetuya** [comment]
@nerik this is still happening to me in the `2.6.0-dev5` version. 
![screenshot 2018-07-20 09 59 33](https://user-images.githubusercontent.com/355597/43003756-efd2fc26-8c03-11e8-82dd-d89d05c77a4a.png)

**Comment by nerik** [comment]
@enriquetuya Managed to reproduce in Firefox and fixed.
