### ISSUE TITLE
Legacy workspace loading issue

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#891]
When loading workspace of an old format I was expecting it to fail and display nothing on the map, instead it showed me the default workspace. I think the correct way to do is to show a pop-up stating that an error occurred when loading the workspace.

**Comment by nerik** [comment]
@enriquetuya I have implemented the following: trying to load a legacy workspace will trigger a warning banner (message is exposed in literals.json):

<img width="1280" alt="screen shot 2018-05-25 at 13 07 44" src="https://user-images.githubusercontent.com/1583415/40541710-30f93b4c-601d-11e8-83de-83a6404910b6.png">

And the map will continue loading with the default workspace. I believe this is more user-friendly than displaying an empty/broken map - also I don't know what is a 'nothing' workspace, just the basemap? We can discuss that, let me know.
