### ISSUE TITLE
Remove fill of polygons? Style in workspace.

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#896]
We need a way of styling polygons so we can only display the line and not the fill color. This will be used for all the layers that are displayed as default: EEZ, Protected Planet.

**Comment by enriquetuya** [comment]
@nerik how can I do this with the current implementation in the `mabbox` branch?

**Comment by nerik** [comment]
@enriquetuya putting back to 'In Progress' as there is an issue with the fix

**Comment by enriquetuya** [comment]
Tried it out, it works.
