### ISSUE TITLE
Graticules are not displaying

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#919]
On version `2.6.0-dev5` when clicking on graticules nothing comes up

![screenshot 2018-07-20 10 40 31](https://user-images.githubusercontent.com/355597/43005498-712fb192-8c09-11e8-8fb2-651fe70b4ee8.png)

Maybe relates with: https://github.com/GlobalFishingWatch/map-client/issues/916

**Comment by nerik** [comment]
I am not able to reproduce this, nor #916. 
Could you please reload the map, go to dev tools, network tab, clear everything, activate graticules, and send me a a snapshot of what you see in the network tab ? Thanks.

**Comment by enriquetuya** [comment]
Weird. this is now working with `2.6.0-dev6`
