### ISSUE TITLE
Pinned Vessels Info icon highlight issue

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#922]
When you have multiple vessels pinned and you click on the vessel info icon, all info icons get highlighted. The expected behaviour is that only the icon selected highlights. 

![screenshot 2018-07-20 10 51 13](https://user-images.githubusercontent.com/355597/43005988-d66dee2e-8c0a-11e8-9d80-b89ec7e33f92.png)

Tested using version `2.6.0-dev5` using the following workspace: 
http://mapbox.world-fishing.globalfishingwatch.org/map/workspace/udw-v2-56a96d34-87f4-456d-b2a7-9f189d06d684

**Comment by nerik** [comment]
Fixed in 2.6.0-dev6
