### ISSUE TITLE
Filter list style issue

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#923]
When creating a filter they display with an incorrect style. Check image below. Tested with version `2.6.0-dev5`

![filter_issue](https://user-images.githubusercontent.com/355597/43006163-6133fbf2-8c0b-11e8-8ad7-12af65623400.png)

Check the filter in the following workspace: 
http://mapbox.world-fishing.globalfishingwatch.org/map/workspace/udw-v2-021f5600-68b7-4d45-9edc-bfe02fd52e49

**Comment by nerik** [comment]
Fixed in 2.6.0-dev6
