### ISSUE TITLE
Incorrect list of layers that have filters

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#924]
Tested in version `2.6.0-dev5`. 
When clicking on create layer you get a list of all the `activity layers` not only the ones that have filters. `encounters` shouldn't be there. 

Tested with: http://mapbox.world-fishing.globalfishingwatch.org/map/workspace/vizz-default-workspace-v16
![screenshot 2018-07-20 10 56 10](https://user-images.githubusercontent.com/355597/43006280-ad1f8c84-8c0b-11e8-917e-27c3837b5f92.png)

**Comment by nerik** [comment]
Fixed in 2.6.0-dev6
