### ISSUE TITLE
Issue displaying timestamp in VIIRS layer

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#925]
The timestamp field is displaying in milis instead of `Jan 5th 2017 2:27 AM UTC` in the VIIRS laye, this was solved on the `legacy-master` back then.  Tested in version `2.6.0-dev5`
http://mapbox.world-fishing.globalfishingwatch.org/map/workspace/udw-v2-44704067-cc9c-4607-a918-62a6b76dd08a

**Comment by nerik** [comment]
Fixed in 2.6.0-dev6

**Comment by nerik** [comment]
Fixed in 2.6.0-dev6
