### ISSUE TITLE
Embeded default workspace still `jumps`

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#927]
When going to the default map : http://mapbox.world-fishing.globalfishingwatch.org/map/ there is still a change in the zoom of the map. See video below. 

Tested with `2.6.0-dev6`

![ezgif-3-986369db00](https://user-images.githubusercontent.com/355597/43019803-8505f34a-8c34-11e8-9d7e-b52c4d6855af.gif)

**Comment by nerik** [comment]
Fixed in 2.6.0-dev7
