### ISSUE TITLE
When clicking on search result the zoom into place and time is not working correctly

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#929]
1 Go to http://mapbox.world-fishing.globalfishingwatch.org
2 Search for `MARSHALLS203`
3 click on the result. You will be taken to beginning of 2012 and the vessel is not displayed. 

Compare to production that uses the same tileset: http://globalfishingwatch.org/map/

Tested with `2.6.0-dev6`

**Comment by nerik** [comment]
Yet another issue related to dateline... Fixed in 2.6.0-dev7
