### ISSUE TITLE
Don't take the user out of the current view when selecting a search result

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#930]
Relates to https://github.com/GlobalFishingWatch/map-client/issues/929

We should give the user the option to go to the vessel or stay in the current view when selecting a search result. This came up during the SF workshop. Specially while investigating encounters. The users wanted to stay in the same view and try to search another known vessel, but since selecting a search results takes you out of the time and location made it impossible. 

Updated Description based on comment: 
https://github.com/GlobalFishingWatch/map-client/issues/930#issuecomment-416272922

![vessel info icons](https://user-images.githubusercontent.com/38662877/44669851-603c3000-aa21-11e8-8a97-d89583e64cec.png)

* [x] Disable the `auto-center` feature. 
* [x] Add the `center` on map feature when clicking the crosshair in the vessel description. I would avoid center on time for now.
* [ ] Add the `center` on map feature when clicking the crosshair in the pin vessel section (only applies for vessel, not fleets of course). I would avoid center on time for now.
* [x] Change the delete icon in the `pinned vessel section` with `un-pin` icon.
* [x] Change the pin icon style on vessel-information.

**Comment by nerik** [comment]
My take:
Disable this, and add a target button to trigger the same feature directly in the vessel info panel (the one that appears at the bottom of layers, etc)

**Comment by satellitestudiodesign** [comment]
As @nerik suggests and @enriquetuya and I discussed on a previous meeting, we shouldn't trigger the zoom/pan automatically. So let's add an icon to trigger it on the info panel and vessel list. 

Bonus. I changed the icon for deleting a vessel it from the list to make more clear the pin/unpin relation.

![vessel info icons](https://user-images.githubusercontent.com/38662877/44669851-603c3000-aa21-11e8-8a97-d89583e64cec.png)

**Comment by nerik** [comment]
@enriquetuya @satellitestudiodesign Currently, clicking on a search result also changes time boundaries to "fit" the selected tracks. We should keep this I think, but just wanted to check

**Comment by nerik** [comment]
@enriquetuya We propose the following:
The target button works for *both* space and time, ie when clicking on it both viewport and time span adapt.
After a search we remove both auto fit for space and time. 
- on the new Timebar we'll have a visual clue if a track is out of boundaries, that it exists either on the left or on the right (with the track color), so problem solved
- as a temporary fix, we will highlight visually the target button, when the result of a search result is out of time boundaries.
