### ISSUE TITLE
How do I add a new static layer from carto? 

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#932]
Which is the correct way to add a new layer from carto that doesn't have vizz.json support? Could you please include a json example? Also, vizz.json legacy layers are supported?

**Comment by nerik** [comment]
I wrote a recap here, lmk if you need me to walk you through this:
https://github.com/GlobalFishingWatch/map-client/blob/develop/documentation/layers.md

**Comment by enriquetuya** [comment]
@nerik so it doesn't matter if it is a layer we only want to display in a single workspace I have to do that in the https://github.com/GlobalFishingWatch/map-client/blob/develop/app/src/map/gl-styles/style.json file, there is no way of declaring a source in another way for `testing` or `one-time` workspaces?

**Comment by nerik** [comment]
@enriquetuya We can do that. I can add a simple mechanism to instantiate an "unknown" layer from a workspace with a default GL style, should be doable in 1-2 hours.
We should first have a quick chat about the use cases for that. What is the level of priority for this ?

**Comment by enriquetuya** [comment]
@nerik let me list some use cases for you to understand why I requested this:

- 1st when doing presentations to different governments for the transparency program we usually create special workspaces that have layers that are not present on the map. For example with Peru (the workspace is private so I'll send it over afterwards) we have the `lineas referenciales` (lines) and `restricted zones` (polygons). For this we use the `vizz.json` from Carto. I've checked an our version of carto and also the public version of carto still support this format.

NOTE: We need to check that those workspace are backward compatible, I suspect they are not. 
 
- 2nd handle quick requests from researchers. We usually get contacted by friend NGO or researchers and ask some help for displaying polygons on map. This could be covered by `geojson` and with the `WMS` as custom layers, so I'm not that worried about this one. 

Base on the 1st, unless you can think of a workaround for achieving that goal, this is high priority, since we need to have those workspaces running when we are out and have the ability to quickly generate new ones for other countries.

**Comment by nerik** [comment]
@enriquetuya Will close for now, but this is something we'll need to rediscuss as not everybody's happy with the implemented GL JSON format
