### ISSUE TITLE
A user needs to have a way a of clearing the UI so the right menu is not shown so the user can do media materials for blogs or presentations

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#941]
We currently have the embedded mode that cleans up the UI a bit for doing videos for media: http://globalfishingwatch.org/map/?embedded=true but is kind of a hack and you don't have a way of seeing vessel information if you are interested in seeing it. Also it shows a fullscreen icon that break everything when you click on it.

### Designs

We tweaked a bit the sidebar, making the first element narrower (`height: 72px`).
Now it also includes the mini-globe, so we can remove it from the bottom-left corner.

![group 7](https://user-images.githubusercontent.com/38662877/43784476-869f6ee6-9a64-11e8-888b-0e28f08aa4f9.png)

### TASKS

* [x] Move mini globe to the right menu.
* [x] Add the arrow to transition the right menu to show/hidden.

**Comment by satellitestudiodesign** [comment]
I think we should simple add an arrow to keep it consistent with the mini-globe's panel behaviour.

![hide side panel](https://user-images.githubusercontent.com/38662877/43576091-c2266c64-9648-11e8-881d-e6bbb173b2c3.png)

**Comment by enriquetuya** [comment]
@satellitestudiodesign I like it

**Comment by satellitestudiodesign** [comment]
We tweaked a bit the sidebar, making the first element narrower (`height: 72px`).
Now it also includes the mini-globe, so we can remove it from the bottom-left corner.

![group 7](https://user-images.githubusercontent.com/38662877/43784476-869f6ee6-9a64-11e8-888b-0e28f08aa4f9.png)

**Comment by enriquetuya** [comment]
@nerik with version `3.0.0-dev9` you experience the following when you are zoomed out: 
![screenshot 2018-08-16 10 29 22](https://user-images.githubusercontent.com/355597/44212937-0bf0a080-a143-11e8-8c95-7af5e44d2562.png)

@nerik with version `3.0.0-dev9` I see a white line on the right edge when I load a workspace: http://mapbox.world-fishing.globalfishingwatch.org/map/workspace/townhall-mapbox-v1
![screenshot 2018-08-16 10 29 41](https://user-imas.githubusercontent.com/355597/44213066-45c1a700-a143-11e8-81e5-788da0692f56.png) 


@satellitestudiodesign we need to review the case where you have the back button you end up having `> <` that is a bit weird
 ![screenshot 2018-08-16 10 30 26](https://user-images.githubusercontent.com/355597/44212929-05fabf80-a143-11e8-90cc-b0184a81865f.png)

**Comment by enriquetuya** [comment]
@nerik another issue happens when the menu is collapsed and you select a vessel. Check how the close circle displays at the right edge.
![ezgif-5-0b716794f5](https://user-images.githubusercontent.com/355597/44213757-d482f380-a144-11e8-8992-21761819c8f1.gif)

I don't know which is the correct behavior:
1- When user selects a vessel, auto show the right menu with the information of the vessel. 
2- Fix the issue and don't show the circle when collapsed.

**Comment by satellitestudiodesign** [comment]
@enriquetuya I agree, the two arrows looks really weird. I tried not to change too much but I agree this should be changed. For me, the cleanest way of switching between the main 3 panels is adding a simple close button and removing the icons (also, the back + title group always looked weird to me).

![new - monthly copy](https://user-images.githubusercontent.com/38662877/44665817-26fec280-aa17-11e8-9c2a-c20ae95a714a.png)

@nerik About the information of a clicked vessel, we should show the right menu automatically.

**Comment by nerik** [comment]
@enriquetuya Checked with Juanca: we remove the icons
