### ISSUE TITLE
The auto-color cycling should only happen when pinning

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#964]
Tested on `3.0.0-dev17`. With the feature introduced in https://github.com/GlobalFishingWatch/map-client/pull/963 the colors change every time you select a vessel. I would change **the behavior so that only happen when you pin a vessel**. If not the user has a maybe `disorienting` experience since every click he does over a track has a different color.

**Comment by nerik** [comment]
But then we would have the same track changing color for no apparent reason, isn't that a bit confusing too?
Maybe @satellitestudiodesign can help?

**Comment by enriquetuya** [comment]
@satellitestudiodesign @nerik I think that only cycling color after you click `pin` will make the user know that the `pin was successful` and that it will be for the user a `known effect` after the first time he/she uses the feature.

**Comment by satellitestudiodesign** [comment]
I agree with @enriquetuya, let's change to a new color only when a vessel is pinned, not every time a vessel is selected.

**Comment by nerik** [comment]
Just to be clear on the proposed solution:
- user clicks on a vessel, track is pink. User pins it, track is still pink.
- user clicks on another vessel, track is green. User closes the vessel panel.
- user clicks on another vessel, track is still green
@enriquetuya @satellitestudiodesign

**Comment by satellitestudiodesign** [comment]
Exactly

**Comment by enriquetuya** [comment]
@satellitestudiodesign @nerik I was thinking more like:

- user clicks on a vessel, track is `pink`. User pins it, track is `next-pin-vessel-color`.
- user clicks on another vessel, track is `pink`. User closes the vessel panel.
- user clicks on another vessel, track is still `pink`
